### ISSUE TITLE
Incompatible message for Contao 4.4

### ISSUE THREAD

**Issue by jammon88** [agoat/contao-piwikanalytics-bundle#8]
Hi agoat

Have you planed to support Contao 4.4? I become a incompatible message when I want to install the plugin from Contao Manager.

Kind regards

Jammon

**Comment by agoat** [comment]
> Have you planed to support Contao 4.4?

The extension is working with Contao 4.4.x. But currently it's not installable with the Contao Manager. 

However, I intend to add support for the Contao manager over the next two months.

**Comment by agoat** [comment]
This plugin is now (Version `1.1.0`+) installable through the Contao Manager.
